package config

import (
	"fmt"
	"strings"

	"github.com/BurntSushi/toml"
)

// Parse decodes, defaults, and validates the configuration encoded in
// data: unknown keys are rejected, PRD-specified defaults are applied
// for keys the document omits, and the result must pass validate()
// before it is returned. It never returns a partial Config: on any
// decode or validation failure the returned Config is nil.
//
// Parse is loadCommitted's extracted body (this is the one place the
// decode/default/validate sequence lives), so any in-memory TOML can
// be parsed the same way the committed file is: interview.materialize
// round-trips its generated bytes through Parse as a self-check before
// ever proposing them as a file, without writing anything to disk.
func Parse(data []byte) (*Config, error) {
	var cfg Config
	md, err := toml.Decode(string(data), &cfg)
	if err != nil {
		return nil, fmt.Errorf("parse configuration: %w", err)
	}
	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		keys := make([]string, len(undecoded))
		for i, k := range undecoded {
			keys[i] = k.String()
		}
		return nil, fmt.Errorf("unknown keys: %s", strings.Join(keys, ", "))
	}

	applyDefaults(&cfg, md)
	if err := cfg.validate(); err != nil {
		return nil, err
	}
	return &cfg, nil
}
