package config

import (
	"fmt"
	"strings"
)

// header is the fixed comment block Render writes atop every
// generated file: it points at the PRD and the future `orch
// configure` entry point, so a human opening the committed file by
// hand knows where policy changes belong (PRD §17: canonical
// configuration changes use Delivery).
const header = "# Orch configuration (PRD §17). Generated by `orch init`; change it through\n" +
	"# `orch configure`, not by hand — canonical configuration changes go through\n" +
	"# a Delivery PR.\n"

// roleOrder lists the six PRD §9 roles, plus the safe review
// downgrade, in the same fixed order validate.go's validateHost walks
// and config.go's Roles struct declares its fields.
var roleOrder = []string{"architect", "scout", "implementer", "specialist", "reviewer", "review_downgrade"}

// roleProfileOf returns role's RoleProfile from r.
func roleProfileOf(r Roles, role string) RoleProfile {
	switch role {
	case "architect":
		return r.Architect
	case "scout":
		return r.Scout
	case "implementer":
		return r.Implementer
	case "specialist":
		return r.Specialist
	case "reviewer":
		return r.Reviewer
	case "review_downgrade":
		return r.ReviewDowngrade
	default:
		// Unreachable: roleOrder is the only caller and is closed.
		return RoleProfile{}
	}
}

// Render renders c as byte-stable canonical TOML: every value is
// written out explicitly, including PRD-defaulted
// concurrency.max_subagents and merge.strategy, so the committed file
// never leaves a policy value implicit. Section order is fixed
// (schema/revision header, concurrency, merge, memhub, metrics, then
// claude before codex — EnabledHosts' and the interview's own
// question-sequence order), only enabled hosts get a [hosts.X] table,
// and output uses LF line endings and %q string quoting throughout.
//
// Render is a hand-written template rather than toml.Encoder
// specifically so golden-file tests can byte-compare its output and
// so field order never depends on struct reflection order. It does
// not validate c — Parse(Render(c)) is the round-trip a caller runs
// as its own self-check (interview.materialize does exactly this
// before ever proposing the bytes as a file).
func Render(c *Config) ([]byte, error) {
	var b strings.Builder
	b.WriteString(header)
	b.WriteByte('\n')
	fmt.Fprintf(&b, "schema_version  = %d\n", c.SchemaVersion)
	fmt.Fprintf(&b, "config_revision = %q\n", c.ConfigRevision)
	b.WriteByte('\n')

	b.WriteString("[concurrency]\n")
	fmt.Fprintf(&b, "max_subagents = %d\n", c.Concurrency.MaxSubagents)
	b.WriteByte('\n')

	b.WriteString("[merge]\n")
	fmt.Fprintf(&b, "strategy = %q\n", c.Merge.Strategy)
	b.WriteByte('\n')

	b.WriteString("[memhub]\n")
	fmt.Fprintf(&b, "mode = %q\n", c.Memhub.Mode)
	b.WriteByte('\n')

	b.WriteString("[metrics]\n")
	fmt.Fprintf(&b, "enabled = %t\n", c.Metrics.Enabled)

	if c.Hosts.Claude != nil {
		renderHost(&b, "claude", c.Hosts.Claude)
	}
	if c.Hosts.Codex != nil {
		renderHost(&b, "codex", c.Hosts.Codex)
	}

	return []byte(b.String()), nil
}

// renderHost appends name's six [hosts.name.roles.*] tables to b, in
// roleOrder.
func renderHost(b *strings.Builder, name string, h *Host) {
	for _, role := range roleOrder {
		p := roleProfileOf(h.Roles, role)
		b.WriteByte('\n')
		fmt.Fprintf(b, "[hosts.%s.roles.%s]\n", name, role)
		fmt.Fprintf(b, "model  = %q\n", p.Model)
		fmt.Fprintf(b, "effort = %q\n", p.Effort)
	}
}
