package config

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/BurntSushi/toml"
)

// localHeader is the fixed comment block RenderLocal writes atop every
// generated machine-local override file: it names the owning command
// (Render's committed-file header names `orch configure` instead) so a
// human opening the file by hand knows configure-local is the repair
// tool for anything wrong with it (contract call 5).
const localHeader = "# Orch machine-local overrides (PRD §17). Generated by\n" +
	"# `orch configure-local`; only the keys below apply on this machine — never\n" +
	"# a substitute for the committed configuration, and never itself committed.\n"

// RenderLocal renders overrides as sparse canonical config.local.toml
// content: only the given keys are written, in render.go's fixed
// section order restricted to the sections a preference key can ever
// belong to (concurrency, metrics, then claude before codex host role
// tables in roleOrder), with the same %q string quoting, LF line
// endings, and byte-stable output Render itself guarantees. Every key
// must be one PreferenceKeys lists; concurrency.max_subagents must
// parse as an integer >= 1 and metrics.enabled as a strconv.ParseBool
// string — the same materialize-grade ingestion checks
// interview.materialize applies to free-text committed-config answers,
// duplicated here since config must not import interview.
//
// overrides must not be empty: an override file that overrides nothing
// is the trivial case callers handle with RemoveLocal instead, so
// RenderLocal treats it as a caller error rather than silently
// rendering just the header.
//
// Self-check: the rendered bytes are re-decoded and every key
// reclassified through leafClasses; the result must equal overrides'
// key set exactly, or RenderLocal fails closed rather than hand a
// caller bytes MergeLocal would itself reject.
func RenderLocal(overrides map[string]string) ([]byte, error) {
	if len(overrides) == 0 {
		return nil, fmt.Errorf("RenderLocal: overrides must not be empty; call RemoveLocal to delete %s instead", LocalOverridePath)
	}
	for key := range overrides {
		if leafClasses[key] != classPreference {
			return nil, fmt.Errorf("RenderLocal: %q is not a preference key", key)
		}
	}

	var b strings.Builder
	b.WriteString(localHeader)

	if v, ok := overrides["concurrency.max_subagents"]; ok {
		n, err := strconv.Atoi(strings.TrimSpace(v))
		if err != nil || n < 1 {
			return nil, fmt.Errorf("RenderLocal: concurrency.max_subagents: %q is not an integer >= 1", v)
		}
		b.WriteByte('\n')
		b.WriteString("[concurrency]\n")
		fmt.Fprintf(&b, "max_subagents = %d\n", n)
	}
	if v, ok := overrides["metrics.enabled"]; ok {
		enabled, err := strconv.ParseBool(strings.TrimSpace(v))
		if err != nil {
			return nil, fmt.Errorf("RenderLocal: metrics.enabled: %q is not a boolean", v)
		}
		b.WriteByte('\n')
		b.WriteString("[metrics]\n")
		fmt.Fprintf(&b, "enabled = %t\n", enabled)
	}

	for _, host := range []string{"claude", "codex"} {
		if err := renderLocalHost(&b, host, overrides); err != nil {
			return nil, err
		}
	}

	data := []byte(b.String())
	if err := selfCheckRenderLocal(data, overrides); err != nil {
		return nil, err
	}
	return data, nil
}

// renderLocalHost appends host's [hosts.host.roles.*] tables to b for
// every role that overrides carries a model or effort value for, in
// roleOrder. Unlike renderHost, a role's table may carry only one of
// the two fields (a sparse override commonly changes just one).
func renderLocalHost(b *strings.Builder, host string, overrides map[string]string) error {
	for _, role := range roleOrder {
		prefix := "hosts." + host + ".roles." + role
		model, hasModel := overrides[prefix+".model"]
		effort, hasEffort := overrides[prefix+".effort"]
		if !hasModel && !hasEffort {
			continue
		}
		if hasModel {
			if err := validateLocalModel(prefix+".model", model); err != nil {
				return err
			}
		}
		if hasEffort && !effortsByHost[host][effort] {
			return fmt.Errorf("RenderLocal: %s.effort: %q is not one of %s", prefix, effort, effortList(host))
		}

		b.WriteByte('\n')
		fmt.Fprintf(b, "[hosts.%s.roles.%s]\n", host, role)
		// Align the "=" the way render.go's renderHost does only when
		// both fields are present together; a sparse single-field
		// override has nothing to align against.
		if hasModel && hasEffort {
			fmt.Fprintf(b, "model  = %q\n", model)
			fmt.Fprintf(b, "effort = %q\n", effort)
		} else if hasModel {
			fmt.Fprintf(b, "model = %q\n", model)
		} else {
			fmt.Fprintf(b, "effort = %q\n", effort)
		}
	}
	return nil
}

// validateLocalModel enforces the same free-text ingestion rule
// interview.materialize's validateModelFreeText applies to a committed
// role answer: non-empty after trimming, and no internal whitespace (an
// exact model version string never contains any).
func validateLocalModel(key, value string) error {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return fmt.Errorf("RenderLocal: %s: model must not be empty", key)
	}
	if strings.ContainsAny(value, " \t\n\r") {
		return fmt.Errorf("RenderLocal: %s: model %q must not contain whitespace", key, value)
	}
	return nil
}

// selfCheckRenderLocal re-decodes data the way MergeLocal would and
// reclassifies every resulting leaf key through leafClasses, requiring
// the classified preference-key set to equal overrides' key set
// exactly.
func selfCheckRenderLocal(data []byte, overrides map[string]string) error {
	var local Config
	md, err := toml.Decode(string(data), &local)
	if err != nil {
		return fmt.Errorf("RenderLocal: self-check: decode: %w", err)
	}
	if undecoded := md.Undecoded(); len(undecoded) > 0 {
		return fmt.Errorf("RenderLocal: self-check: undecoded keys in rendered output: %v", undecoded)
	}

	got := map[string]bool{}
	for _, k := range md.Keys() {
		key := k.String()
		if leafClasses[key] == classPreference {
			got[key] = true
		}
	}
	for key := range overrides {
		if !got[key] {
			return fmt.Errorf("RenderLocal: self-check: rendered output is missing key %q", key)
		}
	}
	for key := range got {
		if _, ok := overrides[key]; !ok {
			return fmt.Errorf("RenderLocal: self-check: rendered output carries unexpected key %q", key)
		}
	}
	return nil
}
